# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da11d4d6448c0812d8a435f0f998ae34604edfd57c674c65e0f0cb3c40154fdce7fddc670efaa2b260fd5e530e9a58253607b466a99f6482cc0a99bbc39a08f7

test:
  secret_key_base: 1cb0162590cac736cf8dea5099beb3102eb7971945af02cbbfba37be8a304bb99bc1281fd4d8d8e6beaaa85b8e985278167eb252018237f5d678c79886f94d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
